app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    
admin:
    path:     /admin
    defaults: { _controller: AppBundle:AdminController }
